# Generated by Django 3.0.6 on 2020-05-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_date of birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
